name: daphnia-env
channels:
  - conda-forge
  - bioconda
dependencies:
  - r-base=4.3.1
  - r-data.table
  - r-foreach
  - r-tidyverse
  - r-viridis
  - r-cowplot
  - r-seqarray
  - r-doparallel
  - r-snprelate
  - r-ggforce
  - r-phylobase
  - r-ggtree
  - r-colortools
  - r-phylotools
  - r-phytools
  - r-thacklr
  - r-treespace
  - r-treetools
  - python=3.8
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - scikit-learn
  - moments
  - pyyaml
  - pip
  - pip:
    - pickle
